//
// Created by Thien Nguyen on 10/7/20.
//

#ifndef PRJ1_PRJ1_H
#define PRJ1_PRJ1_H


#include <cstdint>

typedef struct {
    uint32_t type;      // must be 1
    uint32_t sender;    // sender's id
    uint32_t msg_id;    // the id of message generated by sender
    uint32_t data;      // a dummy integer
} DataMessage;

typedef struct {
    uint32_t type;          // must be 2
    uint32_t sender;        // sender of DataMessage
    uint32_t msg_id;        // the id of Datamessage generated by sender
    uint32_t proposed_seq;  // proposed sequence number
    uint32_t proposer;      // process id of proposer
} AckMessage;


typedef struct {
    uint32_t type;                  // must be 3
    uint32_t sender;                // sender of DataMessage
    uint32_t msg_id;                // the id of Datamessage generated by sender
    uint32_t final_seq;             // proposed sequence number
    uint32_t final_seq_proposer;    // process id of proposer who poposed the final seq
} SeqMessage;

#endif //PRJ1_PRJ1_H
