//
// Created by Thien Nguyen on 10/8/20.
//

#include <queue>
#include <functional>
#include <iostream>

typedef struct {
    uint32_t type;      // must be 1
    uint32_t sender;    // sender's id
    uint32_t msg_id;    // the id of message generated by sender
    uint32_t data;      // a dummy integer
} DataMessage;

typedef struct {
    uint32_t        sequence_number;
    unsigned char   status;     // 0 means undeliverable while 1 means deliverable
    uint32_t        sender;    // sender's id
    uint32_t        msg_id;    // the id of message generated by sender
    uint32_t        data;      // a dummy integer
    uint32_t        proposer;      // process id of proposer
} QueuedMessage;

QueuedMessage makeQM(int seq, int data){
    QueuedMessage t;
    t.sequence_number = seq;
    t.status = 2;
    t.sender = 1;
    t.msg_id = 2;
    t.data = data;
    t.proposer = 2;
    return t;
}

template<typename T> void print_queue(T& q) {
    while(!q.empty()) {
        std::cout << q.top().sequence_number << ":"<< q.top().data << " ";
        q.pop();
    }
    std::cout << '\n';
}

int main(){
    auto cmp = [](QueuedMessage left, QueuedMessage right){
        return left.sequence_number > right.sequence_number;
    };
    std::priority_queue<QueuedMessage, std::vector<QueuedMessage>, decltype(cmp)> q(cmp);

    for (int i : {1,8,5,6,3,4,0,9,7,2}){
        q.push(makeQM(i, i*2));
    }
    print_queue(q);
    return 0;
}